export const locations = [
    {
    type: "group",
    name: "Manhattan",
    items: [
        { name: "Manhattan", value: "Manhattan, New York" },
        {name: "Chinatown", value: "Chinatown, New York"},
        { name: "Financial District (FiDi)", value: "Financial District, New York" },
        { name: "East Harlem", value: "East Harlem, New York" },
        { name: "East Village", value: "East Village, New York" },
        {name: "Flatiron", value: "Flatiron, New York"},
        {name: "Gramercy Park", value: "Gramercy Park, New York"},
        {name: "Greenwich Village", value: "Greenwich Village, New York"},
        {name: "Harlem", value: "Harlem, New York"},
        {name: "Lower East Side", value: "Lower East Side, New York"},
        {name: "Midtown", value: "Midtown, New York"},
        {name: "Midtown South", value: "Midtown South, New York"},
        {name: "Murray Hill", value: "Murray Hill, New York"},
        {name: "Soho", value: "Soho, New York"},
        {name: "Tribeca", value: "Tribeca, New York"},
        {name: "Upper East Side", value: "Upper East Side, New York"},
        {name: "Upper West Side", value: "Upper West Side, New York"},
        {name: "Washington Heights", value: "Washington Heights, New York"},
        {name: "West Village", value: "West Village, New York"},
    ]
    },
    {
    type: "group",
    name: "Brooklyn",
    items: [
        { name: "Brooklyn", value: "Brooklyn, New York, NY" },
        {name: "Bay Ridge", value: "Bay Ridge, New York"},
        {name: "Bedford-Stuyvesant", value: "Bedford-Stuyvesant, New York"},
        {name: "Boerum Hill", value: "Boerum Hill, Brooklyn, New York"},
        {name: "Brooklyn Heights", value: "Brooklyn Heights, New York"},
        {name: "Bushwick", value: "Bushwick, New York"},
        {name: "", value: ""},
        {name: "", value: ""},
        {name: "", value: ""},
        {name: "", value: ""},
        {name: "", value: ""},
        {name: "", value: ""},
        {name: "", value: ""},
        {name: "", value: ""},
        {name: "", value: ""},
        {name: "", value: ""},
    ]
    },
];