export const locations = [
    {
    type: "group",
    name: "Manhattan",
    items: [
        { name: "Manhattan", value: "Manhattan, New York" },
        {name: "Chinatown", value: "Chinatown, New York"},
        { name: "Financial District (FiDi)", value: "Financial District, New York" },
        { name: "East Harlem", value: "East Harlem, New York" },
        { name: "East Village", value: "East Village, New York" },
        {name: "Flatiron", value: "Flatiron, New York"},
        {name: "Gramercy Park", value: "Gramercy Park, New York"},
        {name: "Greenwich Village", value: "Greenwich Village, New York"},
        {name: "Hell's Kitchen", value: "Hell's Kitchen, New York"},
        {name: "Harlem", value: "Harlem, New York"},
        {name: "Hudson Yards", value: "Hudson Yards, New York"},
        {name: "Kips Bay", value: "Kips Bay, New York"},
        {name: "Little Italy", value: "Little Italy, New York"},
        {name: "Lower East Side", value: "Lower East Side, New York"},
        {name: "Midtown", value: "Midtown, New York"},
        {name: "Midtown South", value: "Midtown South, New York"},
        {name: "Murray Hill", value: "Murray Hill, New York"},
        {name: "Soho", value: "Soho, New York"},
        {name: "Tribeca", value: "Tribeca, New York"},
        {name: "Upper East Side", value: "Upper East Side, New York"},
        {name: "Upper West Side", value: "Upper West Side, New York"},
        {name: "Washington Heights", value: "Washington Heights, New York"},
        {name: "West Village", value: "West Village, New York"},
    ]
    },
    {
    type: "group",
    name: "Brooklyn",
    items: [
        { name: "Brooklyn", value: "Brooklyn, New York, NY" },
        {name: "Bay Ridge", value: "Bay Ridge, New York"},
        {name: "Bedford-Stuyvesant", value: "Bedford-Stuyvesant, New York"},
        {name: "Boerum Hill", value: "Boerum Hill, Brooklyn, New York"},
        {name: "Brooklyn Heights", value: "Brooklyn Heights, New York"},
        {name: "Brownsville", value: "Brownsville, New York"},
        {name: "Bushwick", value: "Bushwick, New York"},
        {name: "Carroll Gardens", value: "Carroll Gardens, New York"},
        {name: "Cobble Hill", value: "Cobble Hill, New York"},
        {name: "Crown Heights", value: "Crown Heights, New York"},
        {name: "Downtown", value: "Downtown Brooklyn, New York"},
        {name: "Dumbo", value: "Dumbo, New York"},
        {name: "Flatbush", value: "Flatbush, New York"},
        {name: "Fort Greene", value: "Fort Greene, New York"},
        {name: "Gowanus", value: "Gowanus, New York"},
        {name: "Greenpoint", value: "Greenpoint, New York"},
        {name: "Kensington", value: "Kensington, New York"},
        {name: "Midwood", value: "Midwood, New York"},
        {name: "Park Slope", value: "Park Slope, New York"},
        {name: "Prospect Heights", value: "Prospect Heights, New York"},
        {name: "Red Hook", value: "Red Hook, Brooklyn"},
        {name: "Sunset Park", value: "Sunset Park, New York"},
        {name: "Williamsburg", value: "Williamsburg, New York"},
    ]
    },
    {
    type: "group",
    name: "Queens",
    items: [
        { name: "Queens", value: "Queens, New York, NY" },
        {name: "Astoria", value: "Astoria, New York"},
        {name: "Briarwood", value: "Briarwood, New York"},
        {name: "Corona", value: "Corona, New York"},
        {name: "Elmhurst", value: "Elmhurst, Queens, New York"},
        {name: "Forest Hills", value: "Forest Hills, New York"},
        {name: "Flushing", value: "Flushing, New York"},
        {name: "Fresh Pond", value: "Fresh Pond, New York"},
        {name: "Glendale", value: "Glendale, New York"},
        {name: "Howard Beach", value: "Howard Beach, New York"},
        {name: "Jackson Heights", value: "Jackson Heights, New York"},
        {name: "Jamaica", value: "Jamaica, New York"},
        {name: "Kew Gardens", value: "Kew Gardens, New York"},
        {name: "Long Island City", value: "Long Island City, New York"},
        {name: "Maspeth", value: "Maspeth, New York"},
        {name: "Middle Village", value: "Middle Village, New York"},
        {name: "Ozone Park", value: "Ozone Park, New York"},
        {name: "South Ozone Park", value: "South Ozone Park, New York"},
        {name: "Rego Park", value: "Rego Park, New York"},
        {name: "Ridgewood", value: "Ridgewood, New York"},
        {name: "Sunnyside", value: "Sunnyside, New York"},   
        {name: "Woodhaven", value: "Woodhaven, New York"},
        {name: "Woodside", value: "Woodside, New York"},
    ]
    },
    {
    type: "group",
    name: "Bronx",
    items: [
        {name: "Bronx", value: "Bronx, New York, NY" },
        {name: "Bedford Park", value: "Bedford Park, New York"},
        {name: "Fordham", value: "Fordham, New York"},
        {name: "Kingsbridge", value: "Kingsbridge, New York"},
        {name: "Pelham Bay", value: "Pelham Bay, New York"},
        {name: "Riverdale", value: "Riverdale, New York"},
        {name: "Wakefield", value: "Wakefield, New York"},
        {name: "Woodlawn", value: "Woodlawn, New York"},
    ]
    },
];